services:
  mongodb:
    image: mongo:7.0.2-jammy
    container_name: journal-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: "journal_ai"
    command: >
      mongod 
      --wiredTigerCacheSizeGB=0.25 
      --bind_ip_all 
      --setParameter diagnosticDataCollectionEnabled=false 
      --setParameter ttlMonitorEnabled=false 
      --setParameter cursorTimeoutMillis=30000
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M

volumes:
  mongo-data:
