spring:
  ai:
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "journal_ai"
        collectionName: "vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE
        initialize-schema: true

    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small

      chat:
        options:
          model: gpt-4-turbo
  application:

    name: JournalAI2
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      authentication-database: admin
      database: journal_ai
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      host: journal-mongodb  #Change to env
      port: 27017 #change to env

  cassandra:
    contact-points: localhost:9042
    keyspace-name: my_keyspace
    local-datacenter: datacenter1
    username: admin
    password: admin
    schema-action: create_if_not_exists



  autoconfigure:
    exclude: org.springframework.ai.autoconfigure.vectorstore.cassandra.CassandraVectorStoreAutoConfiguration,org.springframework.ai.autoconfigure.chat.memory.cassandra.CassandraChatMemoryAutoConfiguration

security:
  allowedOrigins:
    - "http://localhost:63342"


jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000

#todo remove defaults and setup environmental variables
#todo move this to dev config not in prod i will have this
admin:
  user:
    enabled: ${ADMIN_ENABLED:true}  # Default false for safety
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@example.com}
    password: ${ADMIN_PASSWORD:admin123}  # Set via env var in production
    preferences:
      therapyFrequency: BIWEEKLY  # Enum value
      language: ENGLISH          # Enum value
      themePreference: DARK      # Enum value
      supportStyle: MINDFUL   # Enum value
      age: 22                    # Integer value
      gender: MALE               # Enum value


management:
  endpoint:
    health:
      show-details: "always"  # Always show detailed health info (safe for internal use)
  endpoints:

    web:
      exposure:
        include: "*"
      base-path: "/monitor"  # Moves all Actuator endpoints under "/monitor"

logging:
  level:
    org.springframework.*: debug
    com.datastax.oss: debug
    org.bson.*: debug
    org.springframework.data: debug
