spring:
  application:
    name: JournalAI2
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: "mongodb://localhost:27017/journalDb"
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
security:
  allowedOrigins: "*"

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000

