spring:
  devtools:
    livereload:
      enabled: true #Disable in production todo refactor this file into seperate profiles
  data:
    mongodb:
      uri: ${MONGO_ATLAS_URL}
      auto-index-creation: true
      database: journal_ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4-turbo
  application:
    name: JournalAI2
  threads:
    virtual:
      enabled: true
  main:
    allow-bean-definition-overriding: true
email:
  sendgrid:
    config:
      apiKey: ${SENDGRID_API_KEY}
      fromEmail: "ahnisaneja@gmail.com"


app:
  base-url: "http://localhost:8080"
  password-reset-url: "/api/v1/auth/reset-password"
security:
  allowedOrigins:
    - "http://localhost:63342"

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000

#todo remove defaults and setup environmental variables
#todo move this to dev config not in prod i will have this
admin:
  vectorstore:
    clear-collection: false
  bootstrap:
    enabled: ${ADMIN_BOOTSTRAP_ENABLED:false}   # Default off for safety (dev only)
    resource: ${ADMIN_BOOTSTRAP_RESOURCE:classpath:/bootstrap/users.json}  # Default to classpath, can point to file:// or even http:// if needed (super flexible)
  user:
    enabled: ${ADMIN_ENABLED:true}  # Default false for safety
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@example.com}
    password: ${ADMIN_PASSWORD:admin123}  # Set via env var in production
    preferences:
      reportFrequency: BIWEEKLY  # Enum value
      language: ENGLISH          # Enum value
      themePreference: DARK      # Enum value
      supportStyle: MINDFUL   # Enum value
      age: 22                    # Integer value
      gender: MALE               # Enum value


management:
  endpoint:
    health:
      show-details: "always"  # Always show detailed health info (safe for internal use)
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/monitor"  # Moves all Actuator endpoints under "/monitor"

logging:
  level:
    com.sendgrid.*: debug
    org.springframework.scheduling.annotation: DEBUG
    org.springframework.*: debug
    com.datastax.oss: debug
    org.bson.*: debug
    org.springframework.data: debug


milvus:
  cloud:
    uri: ${MILVUS_CLOUD_URI}
    token: ${MILVUS_CLOUD_TOKEN}
    username: ${MILVUS_CLOUD_USERNAME}
    password: ${MILVUS_CLOUD_PASSWORD}

vector:
  batching:
    enabled: false
  store:
    database-name: ${VECTOR_STORE_DATABASE_NAME:default}
    collection-name: ${VECTOR_STORE_COLLECTION_NAME:vector_store1}
    metric-type: ${VECTOR_STORE_METRIC_TYPE:COSINE}
    index-type: ${VECTOR_STORE_INDEX_TYPE:IVF_FLAT}
    embedding-dimension: ${VECTOR_STORE_EMBEDDING_DIMENSION:1536}
    initialize-schema: ${VECTOR_STORE_INITIALIZE_SCHEMA:true}
